[package]
name = "reddit-feed-archiver"
version = "0.0.1"
authors = ["Jake Marsden <jakemarsdenjm@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
bytes = '1.0.0'
chrono = '0.4.19'
num-format = "0.4.0"
reqwest = '0.11.0'
tokio = { version = '1.0.1', features = ["macros"] }
